version: 1.0.{build}
image: Visual Studio 2017
cache: packages -> **\packages.config
nuget:
  account_feed: false
  project_feed: false
before_build:
- cmd: nuget restore
install:
  nuget sources add -Name AppVeyorAccount -source https://ci.appveyor.com/nuget/restlessmedia-fqb6idr6vwjb -UserName %APPVEYOR_USERNAME% -password "%APPVEYOR_PASSWORD%"
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
  release: SqlBuilder-v$(appveyor_build_version)
  description: 'SqlBuilder v$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: '%GITHUB_AUTHTOKEN%'
  artifact: /.*\.nupkg/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
